name: Checking gendiff

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.12]

    steps:
      - uses: actions/checkout@v3

      - name: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{matrix.python-version}}

      - name: install-dependencies
        run: pip install poetry && make install

      - name: check linter
        run: make lint

      - name: testing
        run: make test
